import { walking, birds, campfire, fireworks, carnival, marchingBand, chimeBells, cityTraffic, forest, highway, nightWoods, nycMetro, office, playground, rainThunder, typing, train, river, beach, wind, farm, library, construction, volcano } from "./icons"

export const audioData = [
    { id: 'a1', title: 'Wind', fileName: 'ambient/wind.mp3', icon: wind, isPlaying: false },
    { id: 'a2', title: 'Walking', fileName: 'ambient/walking.mp3', icon: walking, isPlaying: false },
    { id: 'a3', title: 'Campfire', fileName: 'ambient/campfire.mp3', icon: campfire, isPlaying: false },
    { id: 'a4', title: 'Fireworks', fileName: 'ambient/fireworks2.mp3', icon: fireworks, isPlaying: false },
    { id: 'a5', title: 'Marching Band', fileName: 'ambient/marchingBand.mp3', icon: marchingBand, isPlaying: false },
    { id: 'a6', title: 'Birds', fileName: 'ambient/birds.mp3', icon: birds, isPlaying: false },
    { id: 'a7', title: 'Carnival', fileName: 'ambient/carnival.mp3', icon: carnival, isPlaying: false },
    { id: 'a8', title: 'Volcano', fileName: 'ambient/volcano.mp3', icon: volcano, isPlaying: false },
    { id: 'a9', title: 'Chime Bells', fileName: 'ambient/chimeBells.mp3', icon: chimeBells, isPlaying: false },
    { id: 'a10', title: 'City Traffic', fileName: 'ambient/cityTraffic.mp3', icon: cityTraffic, isPlaying: false },
    { id: 'a11', title: 'Library', fileName: 'ambient/library.mp3', icon: library, isPlaying: false },
    { id: 'a12', title: 'Forest', fileName: 'ambient/forest.mp3', icon: forest, isPlaying: false },
    { id: 'a13', title: 'Highway', fileName: 'ambient/highway3.mp3', icon: highway, isPlaying: false },
    { id: 'a14', title: 'Night Woods', fileName: 'ambient/nightWoods.mp3', icon: nightWoods, isPlaying: false },
    { id: 'a15', title: 'NYC Metro', fileName: 'ambient/nycMetro.mp3', icon: nycMetro, isPlaying: false },
    { id: 'a16', title: 'Office', fileName: 'ambient/office.mp3', icon: office, isPlaying: false },
    { id: 'a17', title: 'Playground', fileName: 'ambient/playground.mp3', icon: playground, isPlaying: false },
    { id: 'a18', title: 'Farm', fileName: 'ambient/farm.mp3', icon: farm, isPlaying: false },
    { id: 'a19', title: 'Rain Thunder', fileName: 'ambient/rainThunder.mp3', icon: rainThunder, isPlaying: false },
    { id: 'a20', title: 'Typing', fileName: 'ambient/typing.mp3', icon: typing, isPlaying: false },
    { id: 'a21', title: 'Train', fileName: 'ambient/train.mp3', icon: train, isPlaying: false },
    { id: 'a22', title: 'River', fileName: 'ambient/river.mp3', icon: river, isPlaying: false },
    { id: 'a23', title: 'Contruction', fileName: 'ambient/construction.mp3', icon: construction, isPlaying: false },
    { id: 'a24', title: 'Beach', fileName: 'ambient/beach.mp3', icon: beach, isPlaying: false },
]